### ISSUE TITLE
not working...

### ISSUE THREAD

**Issue by FHD100** [rols1/TuneIn2017#2]
plug-in is not working. 
When you click on any readio channel it keeps loading and thats it, doesn't work

**Comment by rols1** [comment]
please put the plugin-log (../Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.plugins.tunein2017.log) here. I will take a look at it.
/R

**Comment by FHD100** [comment]
There you go! :)
[com.plexapp.plugins.tunein2017.log](https://github.com/rols1/TuneIn2017/files/1509157/com.plexapp.plugins.tunein2017.log)

**Comment by rols1** [comment]
could you please make a try with English as choosen language?
I'm not shure, but the reason may be a code-problem with the localisation-strings.
I don't need a new log for this try.

**Comment by rols1** [comment]
Great.
A fix for this bug comes with the nex update.

You are welcome to support the the translation project for this plugin (no supporter for arabic until yet).
Please take a look at the Plex forum:
https://forums.plex.tv/discussion/288260/rel-tunein2017
Contextes and pics you can find in the wicki:
https://github.com/rols1/TuneIn2017/wiki/Pictures-and-Contexts-for-the-Localisation-Project
/R
